const typography = {
  H1: {
    fontSize: '3rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '60px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  H2: {
    fontSize: '2.5rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '50px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  H3: {
    fontSize: '2.0625rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '41px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  H4: {
    fontSize: '1.75rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '35px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  H5: {
    fontSize: '1.75rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '35px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  H6: {
    fontSize: '1.1875rem',
    fontFamily: 'Domaine, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  BodyBase: {
    fontSize: '1rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  BodyLarge: {
    fontSize: '1.125rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  BodySmall: {
    fontSize: '0.8125rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  BodyXSmall: {
    fontSize: '0.6875rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  SubheaderBase: {
    fontSize: '1rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  SubheaderLarge: {
    fontSize: '1.125rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  SubheaderSmall: {
    fontSize: '0.8125rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  SubheaderXSmall: {
    fontSize: '0.6875rem',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamBaseBold: {
    fontSize: '0.875rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamBaseBook: {
    fontSize: '0.875rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamSmallBold: {
    fontSize: '0.75rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamSmallBook: {
    fontSize: '0.75rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamXSmallBook: {
    fontSize: '0.6875rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  GothamOverline: {
    fontSize: '0.6875rem',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '17px',
    textTransform: 'uppercase',
    textDecorationLine: 'none',
  },
}

export default typography;
