const typography = {
  // Domaine Display headers (Figma: H1-H6 with 700/400 weights)
  'H1-700': {
    fontSize: '48px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '60px',
    letterSpacing: '0.96px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H1-400': {
    fontSize: '48px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '60px',
    letterSpacing: '0.96px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H2-700': {
    fontSize: '40px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '50px',
    letterSpacing: '0.4px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H2-400': {
    fontSize: '40px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '50px',
    letterSpacing: '0.4px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H3-700': {
    fontSize: '33px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '41px',
    letterSpacing: '0.33px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H3-400': {
    fontSize: '33px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '41px',
    letterSpacing: '0.33px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H4-700': {
    fontSize: '28px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '35px',
    letterSpacing: '0.28px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H4-400': {
    fontSize: '28px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '35px',
    letterSpacing: '0.28px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H5-700': {
    fontSize: '23px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '29px',
    letterSpacing: '0.23px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H5-400': {
    fontSize: '23px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '29px',
    letterSpacing: '0.23px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H6-700': {
    fontSize: '19px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '24px',
    letterSpacing: '0.19px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'H6-400': {
    fontSize: '19px',
    fontFamily: 'Domaine Display, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: '0.19px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham Narrow - Large (L)
  'GothamN-L-700': {
    fontSize: '18px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-L-500': {
    fontSize: '18px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-L-400': {
    fontSize: '18px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-L-300': {
    fontSize: '18px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '27px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham Narrow - Base (B)
  'GothamN-B-700': {
    fontSize: '16px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-B-500': {
    fontSize: '16px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-B-400': {
    fontSize: '16px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-B-300': {
    fontSize: '16px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham Narrow - Small (S)
  'GothamN-S-700': {
    fontSize: '13px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-S-500': {
    fontSize: '13px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-S-400': {
    fontSize: '13px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-S-300': {
    fontSize: '13px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '20px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham Narrow - XSmall (XS)
  'GothamN-XS-700': {
    fontSize: '11px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-XS-500': {
    fontSize: '11px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-XS-400': {
    fontSize: '11px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'GothamN-XS-300': {
    fontSize: '11px',
    fontFamily: 'Gotham Narrow, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham (regular width) - Large (L)
  'Gotham-L-700': {
    fontSize: '18px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-L-500': {
    fontSize: '18px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-L-400': {
    fontSize: '18px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-L-300': {
    fontSize: '18px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '24px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham - Base (B)
  'Gotham-B-700': {
    fontSize: '14px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-B-500': {
    fontSize: '14px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-B-400': {
    fontSize: '14px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-B-300': {
    fontSize: '14px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '21px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham - Small (S)
  'Gotham-S-700': {
    fontSize: '12px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-S-500': {
    fontSize: '12px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-S-400': {
    fontSize: '12px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-S-300': {
    fontSize: '12px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '18px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Gotham - XSmall (XS)
  'Gotham-XS-700': {
    fontSize: '11px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-XS-500': {
    fontSize: '11px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-XS-400': {
    fontSize: '11px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },
  'Gotham-XS-300': {
    fontSize: '11px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: '17px',
    textTransform: 'none',
    textDecorationLine: 'none',
  },

  // Overline (Figma shows Gotham Base Bold)
  Overline: {
    fontSize: '14px',
    fontFamily: 'Gotham, Helvetica, Arial, sans-serif',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '21px',
    letterSpacing: '0px',
    textTransform: 'uppercase',
    textDecorationLine: 'none',
  },
};

export default typography;
